Make use of fetched data (error)
Error: map-function undefined?!? (its a build-in)..
As I see it, the weather-variable is an array, so it should not give any problems :-( .